package config

import (
	"os"
	"path/filepath"
	"testing"
)

// ─── parseVLESSKey: мultiplex и flow параметры ─────────────────────────────

func TestParseVLESSKey_MuxParam_One(t *testing.T) {
	path := filepath.Join(t.TempDir(), "mux.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s&mux=1"
	os.WriteFile(path, []byte(url), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !p.Mux {
		t.Error("Mux должен быть true при mux=1")
	}
}

func TestParseVLESSKey_MuxParam_True(t *testing.T) {
	path := filepath.Join(t.TempDir(), "mux.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s&mux=true"
	os.WriteFile(path, []byte(url), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !p.Mux {
		t.Error("Mux должен быть true при mux=true")
	}
}

func TestParseVLESSKey_MultiplexParam(t *testing.T) {
	path := filepath.Join(t.TempDir(), "mux.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s&multiplex=1"
	os.WriteFile(path, []byte(url), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !p.Mux {
		t.Error("Mux должен быть true при multiplex=1")
	}
}

func TestParseVLESSKey_MuxParam_Zero_FalseByDefault(t *testing.T) {
	path := filepath.Join(t.TempDir(), "nomux.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s"
	os.WriteFile(path, []byte(url), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if p.Mux {
		t.Error("Mux должен быть false если параметр не указан")
	}
}

func TestParseVLESSKey_FlowParameter(t *testing.T) {
	path := filepath.Join(t.TempDir(), "flow.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s&flow=xtls-rprx-vision"
	os.WriteFile(path, []byte(url), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if p.Flow != "xtls-rprx-vision" {
		t.Errorf("Flow = %q, want xtls-rprx-vision", p.Flow)
	}
}

func TestParseVLESSKey_NoFlow_EmptyString(t *testing.T) {
	path := filepath.Join(t.TempDir(), "noflow.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s"
	os.WriteFile(path, []byte(url), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if p.Flow != "" {
		t.Errorf("Flow = %q, want empty", p.Flow)
	}
}

// ─── parseVLESSKey: комментарии в файле ───────────────────────────────────

func TestParseVLESSKey_IgnoresCommentLines(t *testing.T) {
	path := filepath.Join(t.TempDir(), "commented.key")
	content := "# This is a comment\n# Another comment\nvless://uuid@host.com:443?sni=x.com&pbk=k&sid=s\n"
	os.WriteFile(path, []byte(content), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("parseVLESSKey с комментариями вернул ошибку: %v", err)
	}
	if p.Address != "host.com" {
		t.Errorf("Address = %q, want host.com", p.Address)
	}
}

func TestParseVLESSKey_OnlyComments_ReturnsError(t *testing.T) {
	path := filepath.Join(t.TempDir(), "comments_only.key")
	os.WriteFile(path, []byte("# comment 1\n# comment 2\n"), 0644)

	_, err := parseVLESSKey(path)
	if err == nil {
		t.Error("ожидали ошибку для файла только с комментариями")
	}
}

func TestParseVLESSKey_BOMWithComments(t *testing.T) {
	path := filepath.Join(t.TempDir(), "bom_comments.key")
	content := "# generated by app\nvless://uuid@host.com:443?sni=x.com&pbk=k&sid=s\n"
	// BOM в начале
	os.WriteFile(path, append([]byte{0xEF, 0xBB, 0xBF}, []byte(content)...), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("parseVLESSKey с BOM+комментариями вернул ошибку: %v", err)
	}
	if p.Address != "host.com" {
		t.Errorf("Address = %q, want host.com", p.Address)
	}
}

func TestParseVLESSKey_TrailingWhitespace(t *testing.T) {
	path := filepath.Join(t.TempDir(), "trailing.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s  \r\n"
	os.WriteFile(path, []byte(url), 0644)

	_, err := parseVLESSKey(path)
	if err != nil {
		t.Errorf("parseVLESSKey с trailing whitespace вернул ошибку: %v", err)
	}
}

// ─── parseVLESSKey: кэширование ───────────────────────────────────────────

func TestParseVLESSKey_Caching_SameResult(t *testing.T) {
	path := filepath.Join(t.TempDir(), "cached.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s"
	os.WriteFile(path, []byte(url), 0644)

	p1, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("first parse: %v", err)
	}
	p2, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("second parse: %v", err)
	}
	// Кэш должен вернуть тот же объект (тот же адрес)
	if p1.Address != p2.Address || p1.Port != p2.Port {
		t.Errorf("кэшированный результат отличается: %v vs %v", p1, p2)
	}
}

// ─── buildVLESSOutbound: мultiplex ─────────────────────────────────────────

func TestBuildVLESSOutbound_NoMux(t *testing.T) {
	params := &VLESSParams{
		Address:   "example.com",
		Port:      443,
		UUID:      "test-uuid",
		SNI:       "example.com",
		PublicKey: "pubkey",
		ShortID:   "shortid",
		Mux:       false,
	}
	out := buildVLESSOutbound(params)
	if out.Multiplex != nil {
		t.Error("Multiplex должен быть nil если Mux=false")
	}
	if out.Tag != "proxy-out" {
		t.Errorf("Tag = %q, want proxy-out", out.Tag)
	}
	if out.Server != "example.com" {
		t.Errorf("Server = %q, want example.com", out.Server)
	}
}

func TestBuildVLESSOutbound_WithMux(t *testing.T) {
	params := &VLESSParams{
		Address:   "example.com",
		Port:      443,
		UUID:      "test-uuid",
		SNI:       "example.com",
		PublicKey: "pubkey",
		ShortID:   "shortid",
		Mux:       true,
	}
	out := buildVLESSOutbound(params)
	if out.Multiplex == nil {
		t.Fatal("Multiplex должен быть задан если Mux=true")
	}
	if !out.Multiplex.Enabled {
		t.Error("Multiplex.Enabled должен быть true")
	}
	if out.Multiplex.Protocol != "h2mux" {
		t.Errorf("Multiplex.Protocol = %q, want h2mux", out.Multiplex.Protocol)
	}
	if out.Multiplex.MaxStreams != 8 {
		t.Errorf("Multiplex.MaxStreams = %d, want 8", out.Multiplex.MaxStreams)
	}
}

func TestBuildVLESSOutbound_TLS_Reality(t *testing.T) {
	params := &VLESSParams{
		Address:   "srv.example.com",
		Port:      8443,
		UUID:      "myuuid",
		SNI:       "cdn.example.com",
		PublicKey: "realitypubkey",
		ShortID:   "0xabcd",
	}
	out := buildVLESSOutbound(params)
	if out.TLS == nil {
		t.Fatal("TLS должен быть задан")
	}
	if !out.TLS.Enabled {
		t.Error("TLS.Enabled должен быть true")
	}
	if out.TLS.ServerName != "cdn.example.com" {
		t.Errorf("TLS.ServerName = %q, want cdn.example.com", out.TLS.ServerName)
	}
	if out.TLS.Reality == nil || !out.TLS.Reality.Enabled {
		t.Error("TLS.Reality должен быть включён")
	}
	if out.TLS.Reality.PublicKey != "realitypubkey" {
		t.Errorf("Reality.PublicKey = %q", out.TLS.Reality.PublicKey)
	}
	if out.TLS.UTLS == nil || !out.TLS.UTLS.Enabled {
		t.Error("TLS.UTLS должен быть включён")
	}
	if out.TLS.UTLS.Fingerprint != "random" {
		t.Errorf("UTLS.Fingerprint = %q, want random", out.TLS.UTLS.Fingerprint)
	}
}

func TestBuildVLESSOutbound_FlowPreserved(t *testing.T) {
	params := &VLESSParams{
		Address:   "example.com",
		Port:      443,
		UUID:      "uuid",
		SNI:       "sni",
		PublicKey: "key",
		ShortID:   "id",
		Flow:      "xtls-rprx-vision",
	}
	out := buildVLESSOutbound(params)
	if out.Flow != "xtls-rprx-vision" {
		t.Errorf("Flow = %q, want xtls-rprx-vision", out.Flow)
	}
}

// ─── validateVLESSParams: граничные значения портов ───────────────────────

func TestValidateVLESSParams_PortBoundary(t *testing.T) {
	base := &VLESSParams{
		Address: "h.com", UUID: "u", SNI: "s", PublicKey: "k", ShortID: "i",
	}

	cases := []struct {
		port    int
		wantErr bool
	}{
		{0, true},
		{-1, true},
		{65536, true},
		{100000, true},
		{1, false},
		{80, false},
		{443, false},
		{65535, false},
	}
	for _, tc := range cases {
		p := *base
		p.Port = tc.port
		err := validateVLESSParams(&p)
		if (err != nil) != tc.wantErr {
			t.Errorf("validateVLESSParams(port=%d) error=%v, wantErr=%v", tc.port, err, tc.wantErr)
		}
	}
}
