package config

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ─── parseVLESSKey: мultiplex и flow параметры ─────────────────────────────

func TestParseVLESSKey_MuxParam_One(t *testing.T) {
	path := filepath.Join(t.TempDir(), "mux.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s&mux=1"
	os.WriteFile(path, []byte(url), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !p.Mux {
		t.Error("Mux должен быть true при mux=1")
	}
}

func TestParseVLESSKey_MuxParam_True(t *testing.T) {
	path := filepath.Join(t.TempDir(), "mux.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s&mux=true"
	os.WriteFile(path, []byte(url), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !p.Mux {
		t.Error("Mux должен быть true при mux=true")
	}
}

func TestParseVLESSKey_MultiplexParam(t *testing.T) {
	path := filepath.Join(t.TempDir(), "mux.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s&multiplex=1"
	os.WriteFile(path, []byte(url), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !p.Mux {
		t.Error("Mux должен быть true при multiplex=1")
	}
}

func TestParseVLESSKey_MuxParam_Zero_FalseByDefault(t *testing.T) {
	path := filepath.Join(t.TempDir(), "nomux.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s"
	os.WriteFile(path, []byte(url), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if p.Mux {
		t.Error("Mux должен быть false если параметр не указан")
	}
}

func TestParseVLESSKey_FlowParameter(t *testing.T) {
	path := filepath.Join(t.TempDir(), "flow.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s&flow=xtls-rprx-vision"
	os.WriteFile(path, []byte(url), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if p.Flow != "xtls-rprx-vision" {
		t.Errorf("Flow = %q, want xtls-rprx-vision", p.Flow)
	}
}

func TestParseVLESSKey_NoFlow_EmptyString(t *testing.T) {
	path := filepath.Join(t.TempDir(), "noflow.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s"
	os.WriteFile(path, []byte(url), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if p.Flow != "" {
		t.Errorf("Flow = %q, want empty", p.Flow)
	}
}

// ─── parseVLESSKey: комментарии в файле ───────────────────────────────────

func TestParseVLESSKey_IgnoresCommentLines(t *testing.T) {
	path := filepath.Join(t.TempDir(), "commented.key")
	content := "# This is a comment\n# Another comment\nvless://uuid@host.com:443?sni=x.com&pbk=k&sid=s\n"
	os.WriteFile(path, []byte(content), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("parseVLESSKey с комментариями вернул ошибку: %v", err)
	}
	if p.Address != "host.com" {
		t.Errorf("Address = %q, want host.com", p.Address)
	}
}

func TestParseVLESSKey_OnlyComments_ReturnsError(t *testing.T) {
	path := filepath.Join(t.TempDir(), "comments_only.key")
	os.WriteFile(path, []byte("# comment 1\n# comment 2\n"), 0644)

	_, err := parseVLESSKey(path)
	if err == nil {
		t.Error("ожидали ошибку для файла только с комментариями")
	}
}

func TestParseVLESSKey_BOMWithComments(t *testing.T) {
	path := filepath.Join(t.TempDir(), "bom_comments.key")
	content := "# generated by app\nvless://uuid@host.com:443?sni=x.com&pbk=k&sid=s\n"
	// BOM в начале
	os.WriteFile(path, append([]byte{0xEF, 0xBB, 0xBF}, []byte(content)...), 0644)

	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("parseVLESSKey с BOM+комментариями вернул ошибку: %v", err)
	}
	if p.Address != "host.com" {
		t.Errorf("Address = %q, want host.com", p.Address)
	}
}

func TestParseVLESSKey_TrailingWhitespace(t *testing.T) {
	path := filepath.Join(t.TempDir(), "trailing.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s  \r\n"
	os.WriteFile(path, []byte(url), 0644)

	_, err := parseVLESSKey(path)
	if err != nil {
		t.Errorf("parseVLESSKey с trailing whitespace вернул ошибку: %v", err)
	}
}

func TestReadWriteSecretKey_RoundTripAndPlaintextCompatibility(t *testing.T) {
	path := filepath.Join(t.TempDir(), "secret.key")
	const url = "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s"

	if err := WriteSecretKey(path, url); err != nil {
		t.Fatalf("WriteSecretKey: %v", err)
	}
	got, err := ReadSecretKey(path)
	if err != nil {
		t.Fatalf("ReadSecretKey encrypted: %v", err)
	}
	if got != url {
		t.Fatalf("ReadSecretKey encrypted = %q, want %q", got, url)
	}

	const legacy = "vless://legacy@host.com:443?sni=x.com&pbk=k&sid=s"
	if err := os.WriteFile(path, []byte("  "+legacy+"\r\n"), 0644); err != nil {
		t.Fatalf("write legacy plaintext: %v", err)
	}
	got, err = ReadSecretKey(path)
	if err != nil {
		t.Fatalf("ReadSecretKey plaintext: %v", err)
	}
	if got != legacy {
		t.Fatalf("ReadSecretKey plaintext = %q, want %q", got, legacy)
	}
}

func TestParseVLESSKey_AntiDPIParams(t *testing.T) {
	path := filepath.Join(t.TempDir(), "antidpi.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s&fragment=1&fragment_size=2-4&fp=chrome"
	if err := os.WriteFile(path, []byte(url), 0644); err != nil {
		t.Fatalf("write key: %v", err)
	}
	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("parseVLESSKey: %v", err)
	}
	if !p.Fragment || p.FragmentSize != "2-4" {
		t.Fatalf("fragment params not parsed: %+v", p)
	}
	if p.UTLSFingerprint() != "chrome" {
		t.Fatalf("UTLSFingerprint = %q, want chrome", p.UTLSFingerprint())
	}
}

func TestParseVLESSKey_FragmentDefaultOn(t *testing.T) {
	path := filepath.Join(t.TempDir(), "nofragment.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s"
	if err := os.WriteFile(path, []byte(url), 0644); err != nil {
		t.Fatalf("write key: %v", err)
	}
	p, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("parseVLESSKey: %v", err)
	}
	if !p.Fragment {
		t.Fatal("fragment must be enabled when parameter is absent")
	}
}

func TestParseVLESSKey_FragmentCanBeDisabled(t *testing.T) {
	for _, value := range []string{"0", "false"} {
		t.Run(value, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "fragment-off.key")
			url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s&fragment=" + value
			if err := os.WriteFile(path, []byte(url), 0644); err != nil {
				t.Fatalf("write key: %v", err)
			}
			p, err := parseVLESSKey(path)
			if err != nil {
				t.Fatalf("parseVLESSKey: %v", err)
			}
			if p.Fragment {
				t.Fatalf("fragment must be disabled when parameter is %q", value)
			}
		})
	}
}

// ─── parseVLESSKey: кэширование ───────────────────────────────────────────

func TestParseVLESSKey_Caching_SameResult(t *testing.T) {
	path := filepath.Join(t.TempDir(), "cached.key")
	url := "vless://uuid@host.com:443?sni=x.com&pbk=k&sid=s"
	os.WriteFile(path, []byte(url), 0644)

	p1, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("first parse: %v", err)
	}
	p2, err := parseVLESSKey(path)
	if err != nil {
		t.Fatalf("second parse: %v", err)
	}
	// Кэш должен вернуть тот же объект (тот же адрес)
	if p1.Address != p2.Address || p1.Port != p2.Port {
		t.Errorf("кэшированный результат отличается: %v vs %v", p1, p2)
	}
}

// ─── buildVLESSOutbound: мultiplex ─────────────────────────────────────────

func TestBuildVLESSOutbound_NoMux(t *testing.T) {
	params := &VLESSParams{
		Address:   "example.com",
		Port:      443,
		UUID:      "test-uuid",
		SNI:       "example.com",
		PublicKey: "pubkey",
		ShortID:   "shortid",
		Mux:       false,
	}
	out := buildVLESSOutbound(params)
	if out.Multiplex != nil {
		t.Error("Multiplex должен быть nil если Mux=false")
	}
	if out.Tag != "proxy-out" {
		t.Errorf("Tag = %q, want proxy-out", out.Tag)
	}
	if out.Server != "example.com" {
		t.Errorf("Server = %q, want example.com", out.Server)
	}
}

func TestBuildVLESSOutbound_WithMux(t *testing.T) {
	params := &VLESSParams{
		Address:   "example.com",
		Port:      443,
		UUID:      "test-uuid",
		SNI:       "example.com",
		PublicKey: "pubkey",
		ShortID:   "shortid",
		Mux:       true,
	}
	out := buildVLESSOutbound(params)
	if out.Multiplex == nil {
		t.Fatal("Multiplex должен быть задан если Mux=true")
	}
	if !out.Multiplex.Enabled {
		t.Error("Multiplex.Enabled должен быть true")
	}
	if out.Multiplex.Protocol != "h2mux" {
		t.Errorf("Multiplex.Protocol = %q, want h2mux", out.Multiplex.Protocol)
	}
	if out.Multiplex.MaxStreams != 8 {
		t.Errorf("Multiplex.MaxStreams = %d, want 8", out.Multiplex.MaxStreams)
	}
}

func TestBuildVLESSOutbound_AntiDPIOptions(t *testing.T) {
	params := &VLESSParams{
		Address:      "example.com",
		Port:         443,
		UUID:         "test-uuid",
		SNI:          "example.com",
		PublicKey:    "pubkey",
		ShortID:      "shortid",
		Fragment:     true,
		FragmentSize: "2-4",
		Fingerprint:  "chrome",
		Mux:          true,
	}
	out := buildVLESSOutbound(params)
	if !out.TCPMultiPath {
		t.Fatal("TCPMultiPath должен быть включён")
	}
	if out.TLS == nil || out.TLS.UTLS == nil || out.TLS.UTLS.Fingerprint != "chrome" {
		t.Fatalf("uTLS fingerprint не применён: %+v", out.TLS)
	}
	if out.TLSFragment == nil || !out.TLSFragment.Enabled || out.TLSFragment.Size != "2-4" {
		t.Fatalf("TLSFragment не применён: %+v", out.TLSFragment)
	}
	raw, err := json.Marshal(out)
	if err != nil {
		t.Fatalf("marshal outbound: %v", err)
	}
	if strings.Contains(string(raw), "tls_fragment") {
		t.Fatalf("tls_fragment must not be emitted for sing-box 1.13.x: %s", raw)
	}
	if out.Multiplex == nil || !out.Multiplex.Padding {
		t.Fatalf("mux padding должен быть включён при mux=1: %+v", out.Multiplex)
	}
}

func TestBuildVLESSOutbound_PlainTLSUsesTLS13(t *testing.T) {
	params := &VLESSParams{
		Address: "plain.example.com",
		Port:    443,
		UUID:    "test-uuid",
		SNI:     "plain.example.com",
	}
	out := buildVLESSOutbound(params)
	if out.TLS == nil {
		t.Fatal("TLS должен быть задан")
	}
	if out.TLS.MinVersion != "1.3" {
		t.Fatalf("MinVersion = %q, want 1.3", out.TLS.MinVersion)
	}
	if len(out.TLS.ALPN) != 2 || out.TLS.ALPN[0] != "h2" || out.TLS.ALPN[1] != "http/1.1" {
		t.Fatalf("ALPN не задан: %#v", out.TLS.ALPN)
	}
}

func TestBuildVLESSOutbound_TLS_Reality(t *testing.T) {
	params := &VLESSParams{
		Address:   "srv.example.com",
		Port:      8443,
		UUID:      "myuuid",
		SNI:       "cdn.example.com",
		PublicKey: "realitypubkey",
		ShortID:   "0xabcd",
	}
	out := buildVLESSOutbound(params)
	if out.TLS == nil {
		t.Fatal("TLS должен быть задан")
	}
	if !out.TLS.Enabled {
		t.Error("TLS.Enabled должен быть true")
	}
	if out.TLS.ServerName != "cdn.example.com" {
		t.Errorf("TLS.ServerName = %q, want cdn.example.com", out.TLS.ServerName)
	}
	if out.TLS.Reality == nil || !out.TLS.Reality.Enabled {
		t.Error("TLS.Reality должен быть включён")
	}
	if out.TLS.Reality.PublicKey != "realitypubkey" {
		t.Errorf("Reality.PublicKey = %q", out.TLS.Reality.PublicKey)
	}
	if out.TLS.UTLS == nil || !out.TLS.UTLS.Enabled {
		t.Error("TLS.UTLS должен быть включён")
	}
	if out.TLS.UTLS.Fingerprint != "random" {
		t.Errorf("UTLS.Fingerprint = %q, want random", out.TLS.UTLS.Fingerprint)
	}
}

func TestBuildVLESSOutbound_FlowPreserved(t *testing.T) {
	params := &VLESSParams{
		Address:   "example.com",
		Port:      443,
		UUID:      "uuid",
		SNI:       "sni",
		PublicKey: "key",
		ShortID:   "id",
		Flow:      "xtls-rprx-vision",
	}
	out := buildVLESSOutbound(params)
	if out.Flow != "xtls-rprx-vision" {
		t.Errorf("Flow = %q, want xtls-rprx-vision", out.Flow)
	}
}

// ─── validateVLESSParams: граничные значения портов ───────────────────────

func TestValidateVLESSParams_PortBoundary(t *testing.T) {
	base := &VLESSParams{
		Address: "h.com", UUID: "u", SNI: "s", PublicKey: "k", ShortID: "i",
	}

	cases := []struct {
		port    int
		wantErr bool
	}{
		{0, true},
		{-1, true},
		{65536, true},
		{100000, true},
		{1, false},
		{80, false},
		{443, false},
		{65535, false},
	}
	for _, tc := range cases {
		p := *base
		p.Port = tc.port
		err := validateVLESSParams(&p)
		if (err != nil) != tc.wantErr {
			t.Errorf("validateVLESSParams(port=%d) error=%v, wantErr=%v", tc.port, err, tc.wantErr)
		}
	}
}

// ─── Plain TLS (без Reality) ───────────────────────────────────────────────
//
// BUG FIX: validateVLESSParams и buildVLESSOutbound теперь поддерживают
// серверы без Reality. До фикса — конфигурация не генерировалась при
// отсутствии SNI/PublicKey/ShortID, приложение падало на старый стейл-конфиг
// и sing-box крашился с FATAL "configure tun interface: file not found".

func TestValidateVLESSParams_PlainTLS_NoPublicKey_OK(t *testing.T) {
	// Новый сервер без Reality — только Address, Port, UUID.
	p := &VLESSParams{Address: "srv.example.com", Port: 443, UUID: "some-uuid"}
	if err := validateVLESSParams(p); err != nil {
		t.Errorf("plain TLS без PublicKey должен проходить валидацию, получили: %v", err)
	}
}

func TestValidateVLESSParams_PlainTLS_WithSNI_OK(t *testing.T) {
	// Plain TLS с SNI но без PublicKey — тоже валидно.
	p := &VLESSParams{Address: "srv.example.com", Port: 443, UUID: "uuid", SNI: "sni.example.com"}
	if err := validateVLESSParams(p); err != nil {
		t.Errorf("plain TLS с SNI без PublicKey должен проходить валидацию, получили: %v", err)
	}
}

func TestValidateVLESSParams_Reality_MissingSNI_Error(t *testing.T) {
	// Reality-режим (PublicKey задан) — SNI обязателен.
	p := &VLESSParams{Address: "h.com", Port: 443, UUID: "u", PublicKey: "k", ShortID: "s"}
	if err := validateVLESSParams(p); err == nil {
		t.Error("Reality без SNI должен давать ошибку")
	}
}

func TestValidateVLESSParams_Reality_MissingShortID_Error(t *testing.T) {
	// Reality-режим (PublicKey задан) — ShortID обязателен.
	p := &VLESSParams{Address: "h.com", Port: 443, UUID: "u", PublicKey: "k", SNI: "s"}
	if err := validateVLESSParams(p); err == nil {
		t.Error("Reality без ShortID должен давать ошибку")
	}
}

func TestBuildVLESSOutbound_PlainTLS_NoReality(t *testing.T) {
	// Plain TLS сервер — Reality должен быть nil, TLS включён.
	params := &VLESSParams{
		Address: "plain-srv.example.com",
		Port:    443,
		UUID:    "test-uuid",
		SNI:     "plain-srv.example.com",
		// PublicKey намеренно пуст — plain TLS
	}
	out := buildVLESSOutbound(params)
	if out.TLS == nil {
		t.Fatal("TLS должен быть задан для plain TLS сервера")
	}
	if !out.TLS.Enabled {
		t.Error("TLS.Enabled должен быть true")
	}
	if out.TLS.Reality != nil {
		t.Error("TLS.Reality должен быть nil для plain TLS сервера (нет PublicKey)")
	}
	if out.TLS.ServerName != "plain-srv.example.com" {
		t.Errorf("TLS.ServerName = %q, want plain-srv.example.com", out.TLS.ServerName)
	}
	if out.TLS.UTLS == nil || !out.TLS.UTLS.Enabled {
		t.Error("TLS.UTLS должен быть включён")
	}
}

func TestBuildVLESSOutbound_Reality_StillWorks(t *testing.T) {
	// Reality-сервер — поведение не должно измениться.
	params := &VLESSParams{
		Address:   "reality-srv.example.com",
		Port:      443,
		UUID:      "uuid",
		SNI:       "cdn.example.com",
		PublicKey: "realitypubkey",
		ShortID:   "0xabcd",
	}
	out := buildVLESSOutbound(params)
	if out.TLS == nil || out.TLS.Reality == nil {
		t.Fatal("Reality должен быть включён при наличии PublicKey")
	}
	if !out.TLS.Reality.Enabled {
		t.Error("Reality.Enabled должен быть true")
	}
	if out.TLS.Reality.PublicKey != "realitypubkey" {
		t.Errorf("Reality.PublicKey = %q, want realitypubkey", out.TLS.Reality.PublicKey)
	}
}
